// DOM integration: node tests/interface.test.mjs <directory containing jsdom>
// Uses in-memory storage; no real player saves or browser automation.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
const require = createRequire(resolve(process.argv[2] || '__pycache__/ui-tools', 'entry.cjs'));
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<div id="game" class="game-container"></div>', { url: 'http://localhost/' });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, localStorage: dom.window.localStorage });
const css = ['style','game-ui','iron-squad','iron-squad-interface'].map(name=>readFileSync(`css/${name}.css`,'utf8')).join('\n');
const sheet = document.createElement('style'); sheet.textContent=css; document.head.append(sheet);
const noop = () => {};
const context = new Proxy({ measureText: () => ({width:40}), createLinearGradient: () => ({addColorStop:noop}), createRadialGradient: () => ({addColorStop:noop}) }, {get:(o,k)=>k in o?o[k]:noop});
dom.window.HTMLCanvasElement.prototype.getContext = () => context;
const { IronSquadGame, SLOT_INFO } = await import('../js/games/iron-squad/index.js');
const { saveSlots } = await import('../js/games/iron-squad/save-slots.js');
const game = Object.create(IronSquadGame); game.container = document.getElementById('game');
for (const method of ['startGameLoop', 'showToast']) game[method] = noop;
Object.assign(game, { width:390, height:664, zoom:1, ctx:context, camera:{x:79360,y:79360}, selectedSaleIds:new Set(), commandActiveUntil:0 });
game.setupUI(); game.activeSlotId = saveSlots.create('UI TEST ONLY').id; game.startFreshGame(false);
game.gold = 100000; game.treasury = 20000; game.awakeningOrbs = 5;
game.rankIndex = 2; game.squad[0].isPersonalGuard = true;
game.squad[0].name = 'テスト兵士'; game.squad[0].hp = Math.floor(game.squad[0].maxHp / 2);
game.squad[1].isDown = true; game.squad[1].hp = 0;
const item = (id, type, stat, n) => ({id,type,name:`検証装備${id}`,tier:1,upgrade:0,stats:{[stat]:n},baseStats:{[stat]:n},color:'#e2dac4'});
const old = item('old','WEAPON','atk',10), better = item('better','WEAPON','atk',30), worse = item('worse','WEAPON','atk',2), helmet = item('helmet','HELMET','def',8);
game.equipped = {weapon:old}; game.inventory = [old,better,worse,helmet];
game.openStrategyModal(true);
const $ = id => document.getElementById(id);
const tick = () => new Promise(resolve => setTimeout(resolve, 5));
const input = (id,value,type='input') => {$(id).value=value; $(id).dispatchEvent(new dom.window.Event(type,{bubbles:true}));};
const entries = () => [...document.querySelectorAll('.roster-entry')];
assert.equal(entries().length,48);
assert.equal(entries().filter(e=>e.open).length,0,'roster initially gives an overview, not 48 full equipment sheets');
const ids = [...document.querySelectorAll('[id]')].map(e=>e.id); assert.equal(new Set(ids).size,ids.length,'moving panels must not duplicate live update IDs');
assert.equal($('strat-gold').textContent,'100,000'); assert.equal($('strat-treasury').textContent,'20,000');
$('tab-strat-troops').click(); assert.equal($('view-strat-troops').classList.contains('hidden'),false);
entries()[0].open = true; await tick();
assert.equal(entries()[0].querySelectorAll('.soldier-equip-slot-btn').length,Object.keys(SLOT_INFO).length,'every slot remains operable in an expanded soldier');
entries()[1].open = true; await tick(); assert.equal(entries().filter(e=>e.open).length,1,'one expanded soldier at a time');
const expandedId = game.uiExpandedSoldierId; game.renderStrategyUI(); await tick();
assert.equal(entries().filter(e=>e.open).length,1); assert.equal(game.uiExpandedSoldierId,expandedId,'selected soldier survives an action redraw');
input('roster-search','テスト兵士'); assert.equal(entries().filter(e=>!e.classList.contains('hidden')).length,1);
input('roster-search','いない兵士'); assert.equal($('roster-empty').classList.contains('hidden'),false);
input('roster-search',''); $('roster-wounded-only').checked=true; $('roster-wounded-only').dispatchEvent(new dom.window.Event('change'));
assert.ok(entries().filter(e=>!e.classList.contains('hidden')).length>=2);
$('tab-econ-scout').click(); assert.equal($('view-econ-scout').classList.contains('hidden'),false); assert.equal($('squad-roster-list').style.display,'none','hiring does not append the full army below candidates');
$('tab-econ-equip').click(); assert.equal($('view-strat-equip').classList.contains('hidden'),false);
input('inventory-slot-filter','weapon','change'); assert.equal(document.querySelectorAll('.inventory-card:not(.hidden)').length,3);
$('inventory-better-only').checked=true; $('inventory-better-only').dispatchEvent(new dom.window.Event('change'));
assert.equal(document.querySelectorAll('.inventory-card:not(.hidden)').length,1);
for (const row of document.querySelectorAll('.inventory-card.hidden')) assert.equal(window.getComputedStyle(row).display,'none','filters must hide cards through the final CSS cascade');
assert.equal(document.querySelector('.inventory-card:not(.hidden)').querySelector('.equip-btn').textContent,'装備');
document.querySelector('.inventory-card:not(.hidden) .equip-btn').click(); assert.equal(game.equipped.weapon.id,'better','reorganized bag still equips through the real handler');
$('inventory-better-only').checked=false; $('inventory-better-only').dispatchEvent(new dom.window.Event('change'));
const weakCard = [...document.querySelectorAll('.inventory-card')].find(e=>e.textContent.includes('検証装備worse'));
weakCard.querySelector('input[type=checkbox]').click(); assert.ok(game.selectedSaleIds.has('worse'));
input('inventory-slot-filter','helmet','change'); assert.ok(game.selectedSaleIds.has('worse'),'hidden selections stay selected and the sell button counts all selected items');
const goldBefore = game.gold; document.querySelector('.sell-selected').click();
assert.ok(!game.inventory.some(i=>i.id==='worse')); assert.ok(game.gold>goldBefore);
input('inventory-slot-filter','','change');
$('tab-econ-roster').click(); input('roster-search',''); $('roster-wounded-only').checked=false; $('roster-wounded-only').dispatchEvent(new dom.window.Event('change'));
const soldier = game.squad[0]; const row = entries().find(e=>e.dataset.soldierId===String(soldier.id));
row.open=true; await tick(); row.querySelector('.soldier-equip-slot-btn').click();
assert.equal($('equipment-transfer-popup').classList.contains('hidden'),false);
assert.equal(document.querySelectorAll('.transfer-slot-tab-btn').length,7);
assert.equal($('strategy-modal').inert,true,'transfer dialog blocks controls behind it');
document.querySelector('.transfer-popup-close-btn').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
assert.equal($('equipment-transfer-popup').classList.contains('hidden'),true); assert.equal($('strategy-modal').inert,false);
row.querySelector('.btn-soldier-detail').click();
assert.equal(game.selectedSoldierDetailId,soldier.id);
const faceBefore=JSON.stringify(soldier.appearance);
assert.equal(document.querySelectorAll('#soldier-detail-host').length,1);
assert.equal(document.querySelectorAll('#soldier-detail-host .soldier-face-portrait').length,1);
assert.match(document.querySelector('.soldier-face-portrait').getAttribute('aria-label'),/素顔/);
game.openSoldierDetail(game.squad[1].id); assert.equal(document.querySelectorAll('#soldier-detail-host').length,1,'individual soldier windows reuse one host');
game.openSoldierDetail(soldier.id); assert.equal(JSON.stringify(soldier.appearance),faceBefore,'switching selected soldiers never rerolls the face');
assert.equal(document.querySelector('.dialog-body').inert,true);
document.querySelector('.btn-close-soldier-detail').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
assert.equal(game.selectedSoldierDetailId,null); assert.equal(document.querySelector('.dialog-body').inert,false); assert.equal($('strategy-modal').classList.contains('hidden'),false);
$('tab-strat-nation').click(); assert.equal($('view-strat-nation').classList.contains('hidden'),false);
const members = document.querySelector('.expedition-members'); members.open=true;
const pick = members.querySelector('.expedition-pick'); const pickedId=pick.dataset.sid, wasPicked=pick.checked; pick.click();
assert.equal(document.querySelector('.expedition-members').open,true,'member picker stays open while selecting soldiers');
assert.equal(game.getExpeditionPicks(Number(pick.dataset.pid)).map(String).includes(pickedId),!wasPicked);
const nextTier = document.querySelector('.btn-danger-tier:not(.active)'); nextTier.click();
assert.equal(document.querySelector('.btn-danger-tier.active').getAttribute('aria-pressed'),'true');
let donations=0; game.donateToTreasury=()=>donations++; $('btn-donate-treasury').click(); assert.equal(donations,1,'donation keeps its action after reparenting');
let heals=0; game.healAllSquad=()=>heals++; $('btn-heal-all').click(); assert.equal(heals,1);
const reserve=game.createNewSoldier();game.reserves.push(reserve);game.renderStrategyUI();
document.querySelector('#reserve-roster-list .mini-btn').click();assert.equal(game.selectedSoldierDetailId,reserve.id);
assert.match(document.querySelector('.soldier-detail-head').textContent,/予備兵/);game.closeSoldierDetail();
game.player.isAdvanced=true; game.player.advancedClass='WARLORD'; game.renderStrategyUI();
assert.match($('btn-promote-player').textContent,/帝皇/,'the existing second awakening stage must be reachable from the UI');
game.player.advancedClass='EMPEROR'; game.awakeningGems=0; game.renderStrategyUI();
assert.match($('btn-promote-player').textContent,/神話帝/); assert.equal($('btn-promote-player').disabled,true,'missing rare gems must be apparent before activating promotion');
game.awakeningGems=1; game.renderStrategyUI(); assert.equal($('btn-promote-player').disabled,false);
game.player.advancedClass='MYTHIC_EMPEROR'; game.renderStrategyUI(); assert.equal($('btn-promote-player'),null,'the final stage shows completion');
game.player.hp=1; game.restTimer=3; game.worldTime=300; game.updateStatsUI();
assert.equal($('player-hp').getAttribute('data-condition'),'critical');
assert.equal($('phase-timer-display').textContent,'待機 3秒'); assert.match($('day-night-badge').textContent,/夜/);
assert.equal(window.getComputedStyle($('player-hp')).color,'var(--ui-danger)','critical HP selects the warning rule rather than the healthy HP rule');
game.restTimer=0; game.player.hp=game.player.maxHp; game.updateStatsUI();
document.querySelector('.btn-expedition-send[data-pid="2"]').click();
assert.equal(game.platoons[2].mission,'expedition','nation screen still dispatches the real selected platoon');
game.saveGame(); const expeditionSave=saveSlots.get(game.activeSlotId).data;
game.resumeSavedGame(expeditionSave); assert.equal(game.platoons[2].mission,'expedition','mission restoration belongs to saved-game loading, not New Game');
game.openStrategyModal(true);
const faceSave=saveSlots.get(game.activeSlotId).data;
assert.ok(faceSave.squad.every(s=>s.appearance?.version===1));
// Snapshot the actual generated DOM for static CSS review (not a browser screenshot).
if (process.env.UI_REVIEW_DIR) {
  const folder = resolve(process.env.UI_REVIEW_DIR); mkdirSync(folder,{recursive:true});
  for (const [name,tab,sub] of [['overview','overview',null],['roster','troops','roster'],['equipment','troops','equip'],['nation','nation',null]]) {
    if(sub) game.rosterManageTab=sub; game._selectStratTab(tab);
    if(name==='roster') for(const row of entries()) row.open=false;
    writeFileSync(resolve(folder,`${name}.html`),`<!doctype html><meta charset="utf-8"><style>${css}</style><div style="width:390px;height:844px;">${game.container.outerHTML}</div>`,'utf8');
  }
}
$('btn-start-next-wave').click(); assert.equal($('strategy-modal').classList.contains('hidden'),true); assert.equal(game.inBattle,true);
console.log('PASS: live DOM navigation, compact army, search, expanded-state retention, seven transfer slots, equipment comparison filters, real equip/sale actions, donation, healing and return to battle');
dom.window.close();
