import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {JSDOM} from '../__pycache__/ui-tools/node_modules/jsdom/lib/api.js';
import {WORLD_SIZE} from '../js/games/iron-squad/world.js';
import {invasionStrength,shouldTriggerRandomRaid,serializeInvasions,drawInvasionRoute} from '../js/games/iron-squad/invasion-rules.js?v=107';
import {wallGeometry,gatePositions,resolveWallMovement,drawFortification,updateGateGuards,serializeGateGuards,townExitReached} from '../js/games/iron-squad/gate-rules.js?v=107';
import {markSoldierDown,updateWounded,syncDragged,rescueUnits} from '../js/games/iron-squad/casualty-rules.js';
const dom=new JSDOM('<div id="game"></div>',{url:'http://localhost/'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,confirm:()=>true,alert:()=>{}});
const noop=()=>{},context=new Proxy({measureText:()=>({width:40}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>k in o?o[k]:noop});window.HTMLCanvasElement.prototype.getContext=()=>context;
const {IronSquadGame}=await import('../js/games/iron-squad/index.js');const {saveSlots}=await import('../js/games/iron-squad/save-slots.js');
const game=Object.create(IronSquadGame);Object.assign(game,{container:document.getElementById('game'),width:390,height:664,zoom:1,ctx:context,camera:{x:WORLD_SIZE/2,y:WORLD_SIZE/2},selectedSaleIds:new Set(),commandActiveUntil:0,joystick:{active:false,dirX:0,dirY:0}});
for(const method of ['startGameLoop','showToast','spawnSparks','spawnDamageText'])game[method]=noop;
game.setupUI();game.activeSlotId=saveSlots.create('INVASION TEST ONLY').id;game.startFreshGame(false);const initial=structuredClone(game.saveGame()),c=WORLD_SIZE/2;
const fresh=()=>{game.resumeSavedGame(structuredClone(initial));game.closeStrategyModal();game.updateSpawns=noop;game.monsters=[];game.currentQuest=null;};
// Regular departures, actual authored origin, warning, bounded arrivals and stronger-friendly scaling.
fresh();game.phase=2;game.phaseTimer=10;game.updateDemonInvasion(1);assert.equal(game.invasions.stage,'idle');game.phase=3;game.phaseTimer=101;game.updateDemonInvasion(1);assert.equal(game.invasions.stage,'idle');game.phaseTimer=100;game.updateDemonInvasion(1);assert.equal(game.invasions.stage,'marching');assert.equal(game.invasions.nextPhase,7);assert.equal(game.invasions.source.x,game.dungeons.find(d=>d.id==='dungeon_demon_castle').entrance.x);
const baselineStrength=invasionStrength(game);const max=game.squad[0].maxHp;game.squad[0].hp=1;assert.equal(invasionStrength(game).hp,baselineStrength.hp,'temporary wounds do not reduce army scaling');game.squad[0].hp=max;
const stronger=invasionStrength({...game,player:{...game.player,maxHp:game.player.maxHp*5,atk:game.player.atk*5},squad:game.squad.map(s=>({...s,maxHp:s.maxHp*5,atk:s.atk*5}))});assert.ok(stronger.hp>baselineStrength.hp*4);assert.ok(stronger.atk>baselineStrength.atk*4);
const outlier=invasionStrength({...game,player:{...game.player,maxHp:1e9,atk:1e9}});assert.ok(outlier.hp<baselineStrength.hp*2,'one exceptional hero does not make recruits face impossible numbers');
game.updateDemonInvasion(24);assert.equal(game.invasions.stage,'marching');game.updateDemonInvasion(1);assert.equal(game.invasions.stage,'battle');assert.ok(game.monsters.length<=40);assert.equal(game.monsters.filter(m=>m.isInvasionCommander).length,1);assert.ok(game.monsters.every(m=>m.x>c&&m.y>c));
const armyCount=game.monsters.length;game.monsters[0].hp-=17;const beforeSave=structuredClone(game.monsters),battle=structuredClone(game.saveGame());game.resumeSavedGame(battle);assert.equal(game.invasions.stage,'battle');assert.equal(game.monsters.filter(m=>m.isDemonInvasion).length,armyCount);assert.equal(game.monsters.find(m=>m.id===beforeSave[0].id).hp,beforeSave[0].hp);
game.completePhase();const resting=structuredClone(game.saveGame()),remaining=game.invasions.remaining;game.resumeSavedGame(resting);assert.equal(game.restMonsters.filter(m=>m.isDemonInvasion).length,armyCount,'rest loads do not duplicate the army');game.updateDemonInvasion(10);assert.equal(game.invasions.remaining,remaining);game.finishRest();
const town=game.dungeons.find(d=>d.id==='royal_castle_town');game.player.x=town.entrance.x;game.player.y=town.entrance.y;game.enterDungeon(town);const paused=game.invasions.remaining;game.updateDemonInvasion(20);assert.equal(game.invasions.remaining,paused);const townSave=structuredClone(game.saveGame());assert.equal(townSave.invasions.mobs.length,armyCount);game.resumeSavedGame(townSave);assert.equal(game.monsters.filter(m=>m.isDemonInvasion).length,armyCount,'saving in town retains the field army');
for(const m of game.monsters)if(m.isDemonInvasion)m.hp=0;const gold=game.gold,treasury=game.treasury;game.updateDemonInvasion(.1);assert.equal(game.invasions.lastResult.outcome,'victory');assert.ok(game.gold>gold&&game.treasury>treasury);const rewarded=game.treasury;game.updateDemonInvasion(.1);assert.equal(game.treasury,rewarded,'victory reward cannot repeat');assert.equal(game.phaseFiscal.defenseRewards,1750);
// Low-frequency random events roll once, respect the gap and cannot overlap a scheduled invasion.
fresh();game.invasions.nextPhase=100;game.phase=8;game.phaseTimer=120;let rolls=0;const random=()=>{rolls++;return 0;};assert.equal(shouldTriggerRandomRaid(game,random),false);game.phaseTimer=1;assert.equal(shouldTriggerRandomRaid(game,random),true);assert.equal(rolls,2);shouldTriggerRandomRaid(game,random);assert.equal(rolls,2);game.baseRaidTriggeredPhase=8;game.phase=15;assert.equal(shouldTriggerRandomRaid(game,random),false);game.phase=16;assert.equal(shouldTriggerRandomRaid(game,random),true);game.invasions.stage='marching';assert.equal(shouldTriggerRandomRaid(game,random),false);
game.invasions.stage='idle';game.phase=16;game.monsters=Array.from({length:40},(_,i)=>({hp:100,x:c+1000+i,y:c,type:'goblin'}));game.triggerBaseRaid();assert.ok(game.monsters.length<=40);assert.equal(game.baseRaidActive,true);game.completeBaseRaid(false);assert.ok(!game.monsters.some(m=>m.isRaidMob));
// The army withdraws cleanly on timeout and stops after the castle is defeated.
fresh();game.phase=3;game.phaseTimer=100;game.startDemonInvasion();game.arriveDemonInvasion();game.invasions.remaining=.1;game.updateDemonInvasion(.2);assert.equal(game.invasions.lastResult.outcome,'timeout');assert.ok(!game.monsters.some(m=>m.isDemonInvasion));game.phase=7;game.startDemonInvasion();game.dungeons.find(d=>d.id==='dungeon_demon_castle').cleared=true;game.updateDemonInvasion(.1);assert.equal(game.invasions.lastResult.outcome,'castle-fallen');assert.equal(game.startDemonInvasion(),false);
// Every wall has wide openings; swept movement blocks solid segments but permits doors and an AI detour.
fresh();const wall=wallGeometry(game);assert.equal(gatePositions(wall).length,5);
const actor=game.player;Object.assign(actor,{x:c+340,y:c+100});assert.equal(resolveWallMovement(game,actor,c+290,c+100),true);assert.ok(actor.x<c+300);
Object.assign(actor,{x:c+340,y:c});assert.equal(resolveWallMovement(game,actor,c+290,c),false);
Object.assign(actor,{x:c+340,y:c+220});assert.equal(resolveWallMovement(game,actor,c+290,c+220),false,'the southeast town route has its own entrance');
const walker={x:c+330,y:c+320,speed:70,radius:12};for(let i=0;i<400;i++){const fromX=walker.x,fromY=walker.y,dx=c-walker.x,dy=c-walker.y,d=Math.hypot(dx,dy);walker.x+=dx/d*7;walker.y+=dy/d*7;resolveWallMovement(game,walker,fromX,fromY,.1);if(Math.hypot(walker.x-c,walker.y-c)<80)break;}assert.ok(Math.hypot(walker.x-c,walker.y-c)<80,'invasion AI passes a gate instead of remaining stuck outside');
// Gate guards share actual escort combat, hit growth, experience and rescued-to-HQ behavior.
const guard=game.gateGuards.find(g=>g.id==='hq_gate_1');assert.ok(guard.isMerchantEscort&&guard.maxHp>400);const hp=guard.maxHp;game.damageTarget(guard,30);assert.ok(guard.hitGrowthPct>0&&guard.maxHp>=hp);
const foe={x:guard.x+15,y:guard.y,hp:1,maxHp:40,atk:1,def:0,radius:10,type:'goblin',speed:0};game.monsters=[foe];guard.atkTimer=0;const oldExp=guard.exp||0;updateGateGuards(game,1);assert.ok(foe.hp<40);assert.ok(guard.minionKills>0||(guard.exp||0)>oldExp||guard.level>1);
game.monsters=[];game.enterDungeon(game.dungeons.find(d=>d.id==='royal_castle_town'));const inner=game.gateGuards.find(g=>g.gateSpace==='royal_castle_town');assert.ok(inner);markSoldierDown(game,inner);game.player.x=inner.x;game.player.y=inner.y;updateWounded(game,0);assert.equal(inner.carrierId,'player');assert.ok(rescueUnits(game).includes(inner));const carriedSave=serializeGateGuards(game).find(g=>g.id===inner.id);assert.equal(carriedSave.gateSpace,'field');assert.ok(carriedSave.x>70000);
game.exitDungeon();assert.equal(inner.gateSpace,'field');game.player.x=c;game.player.y=c;syncDragged(game,.1);updateWounded(game,0);assert.equal(inner.isDown,false);assert.equal(inner.rescuedToBase,true);assert.ok(Math.hypot(inner.homeX-c,inner.homeY-c)<150);const guardsSave=structuredClone(game.saveGame());game.resumeSavedGame(guardsSave);const loaded=game.gateGuards.find(g=>g.id===inner.id);assert.equal(loaded.rescuedToBase,true);assert.equal(loaded.isMerchantEscort,true);
game.enterDungeon(game.dungeons.find(d=>d.id==='royal_castle_town'));game.update(.01);assert.equal(game.currentDungeon?.kind,'town','town entry does not immediately bounce out on the next live frame');const townWall=wallGeometry(game);
for(const gate of gatePositions(townWall)){game.player.x=gate.x+(gate.side==='east'?6:gate.side==='west'?-6:0);game.player.y=gate.y+(gate.side==='south'?6:gate.side==='north'?-6:0);assert.equal(townExitReached(game),true,'all four town gates allow departure');}game.exitDungeon();
game.renderStrategyUI();assert.ok(document.getElementById('nation-defense').textContent.includes('4ウェーブ'));assert.equal(document.getElementById('demon-invasion-banner').closest('.field-alerts').className,'field-alerts');
// Native pixels validate authored walls and route rendering without a browser.
const {createCanvas}=createRequire(resolve('C:/Users/Yoshiyuki/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules','entry.cjs'))('@napi-rs/canvas');const canvas=createCanvas(800,800),ctx=canvas.getContext('2d');ctx.translate(400-c,400-c);drawFortification(ctx,game);assert.ok(ctx.getImageData(0,0,800,800).data.some((v,i)=>i%4===3&&v>0));ctx.resetTransform();game.invasions.stage='marching';game.invasions.eta=12;drawInvasionRoute(ctx,game,x=>(x-c)/150+100,y=>(y-c)/150+100,()=>true);
// Verify a real battle can be won by the initial army, using the live AI and damage rules.
fresh();game.phase=3;game.phaseTimer=100;game.startDemonInvasion();game.arriveDemonInvasion();game.player.x=c;game.player.y=c;
for(let i=0;i<700&&game.invasions.stage==='battle'&&game.player.hp>0;i++)game.update(.1);
assert.equal(game.invasions.lastResult?.outcome,'victory','a fresh army can defeat the adaptive invasion with live combat');
console.log('PASS: periodic adaptive army and live victory, authored departure/ETA, crowd cap, campaign/rest/town saves, one-time fiscal reward, rare-event rolls/gap/cleanup, castle defeat, solid walls/open gates/AI detours, real guard combat/growth/rescue/save and native wall/route pixels');dom.window.close();
