import assert from 'node:assert/strict';
import {JSDOM} from '../__pycache__/ui-tools/node_modules/jsdom/lib/api.js';
import {WORLD_SIZE} from '../js/games/iron-squad/world.js';
import {majorReference,majorInvasionStrength} from '../js/games/iron-squad/invasion-rules.js?v=110';
import {replenishTownGateGuards,serializeGateGuards,serializeGatePosts} from '../js/games/iron-squad/gate-rules.js?v=110';
import {markSoldierDown,updateWounded,syncDragged} from '../js/games/iron-squad/casualty-rules.js';
let simulationTime=0;const originalPerformance=globalThis.performance,originalDateNow=Date.now;Date.now=()=>1700000000000;Object.defineProperty(globalThis,'performance',{configurable:true,value:{now:()=>simulationTime}});
let seed=24701;const originalRandom=Math.random;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const dom=new JSDOM('<div id="game"></div>',{url:'http://localhost/'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,confirm:()=>true,alert:()=>{}});
const noop=()=>{},ctx=new Proxy({measureText:()=>({width:40}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>k in o?o[k]:noop});window.HTMLCanvasElement.prototype.getContext=()=>ctx;
const {IronSquadGame,applyUpgradeStats,SLOT_INFO}=await import('../js/games/iron-squad/index.js');const {saveSlots}=await import('../js/games/iron-squad/save-slots.js');
const game=Object.create(IronSquadGame),c=WORLD_SIZE/2;Object.assign(game,{container:document.getElementById('game'),width:390,height:664,zoom:1,ctx,camera:{x:c,y:c},selectedSaleIds:new Set(),commandActiveUntil:0,joystick:{active:false,dirX:0,dirY:0}});
for(const m of ['startGameLoop','showToast','spawnSparks','spawnDamageText'])game[m]=noop;
game.setupUI();game.activeSlotId=saveSlots.create('MAJOR TEST ONLY').id;game.startFreshGame(false);const initial=structuredClone(game.saveGame());
function fresh(){game.resumeSavedGame(structuredClone(initial));game.closeStrategyModal();game.updateSpawns=noop;game.monsters=[];game.restMonsters=[];game.currentQuest=null;}
function tenthWave(){fresh();for(let i=0;i<10;i++){game.completePhase();for(let j=0;j<8;j++)game.processRestSecond();game.finishRest();game.monsters=[];game.restMonsters=[];}game.invasions.sequence=2;game.phaseTimer=100;return structuredClone(game.saveGame());}
// Major invasions start only after ten complete waves; training can overtake the fixed reference.
fresh();game.phase=10;game.startDemonInvasion();assert.equal(game.invasions.kind,'regular');game.finishDemonInvasion('timeout');game.phase=11;game.startDemonInvasion();assert.equal(game.invasions.kind,'major');assert.equal(game.invasions.eta,35);assert.equal(game.invasions.remaining,125);assert.equal(game.invasions.strength.count,36);assert.equal(game.invasions.nextMajorPhase,19);
const ref=structuredClone(game.invasions.majorReference);game.arriveDemonInvasion();assert.equal(game.monsters.filter(m=>m.isMajorInvasion).length,36);assert.ok(game.monsters.length<=40);assert.ok(game.monsters.some(m=>m.isMajorElite));const campaignSave=structuredClone(game.saveGame());game.resumeSavedGame(campaignSave);assert.equal(game.invasions.kind,'major');assert.deepEqual(game.invasions.majorReference,ref);assert.equal(game.monsters.filter(m=>m.isMajorInvasion).length,36);
game.finishDemonInvasion('timeout');game.phase=15;game.startDemonInvasion();assert.equal(game.invasions.kind,'regular');game.finishDemonInvasion('timeout');game.phase=19;game.player.maxHp=1e8;game.player.atk=1e8;game.startDemonInvasion();assert.equal(game.invasions.kind,'major');assert.deepEqual(game.invasions.majorReference,ref);assert.ok(game.invasions.strength.hp<ref.hp*1.2,'later growth does not copy a newly overpowered hero');
assert.equal(majorReference({hp:1e9,atk:1e9,def:1e9}).hp,220);assert.ok(majorInvasionStrength(ref,100).hp<=ref.hp*3);
// Real passive maintenance for ten waves, then an unattended defense. Preserve one combat participant in retreat.
const ten=tenthWave();game.rankIndex=2;const survivor=game.squad.find(s=>s.soldierClass==='HEAVY')||game.squad[0];survivor.isPersonalGuard=true;game.player.x=c+4000;game.player.y=c+4000;survivor.x=game.player.x-20;survivor.y=game.player.y;
function participate(){const target={x:survivor.x+20,y:survivor.y,hp:1,maxHp:1,type:'goblin',radius:10,atk:1,def:0};game.monsters.push(target);game.performAttack(survivor,target,false,20);}
participate();const originalArmy=[...game.squad];game.startDemonInvasion();game.arriveDemonInvasion();game.phaseTimer=65;let largestLoss=0,lastPhase=game.phase;
let needParticipation=false;for(let i=0;i<2200;i++){simulationTime+=100;game.update(.1);largestLoss=Math.max(largestLoss,originalArmy.filter(s=>s.dead||s.isDown).length);if(game.phase!==lastPhase){lastPhase=game.phase;needParticipation=true;}if(needParticipation&&game.restTimer<=0&&!survivor.dead&&!survivor.isDown){participate();needParticipation=false;}if(game.phase>=13)break;}
const actualDead=originalArmy.filter(s=>s.dead).length;console.log(JSON.stringify({case:'default',largestLoss,actualDead,awakening:survivor.deathlineSkills?.length||0,outcome:game.invasions.lastResult?.outcome}));
assert.ok(largestLoss>=32,'default unattended army suffers catastrophic real casualties');assert.ok(actualDead>=15,'casualties are real HP/down/bleed deaths, not scripted dead flags');assert.ok((survivor.deathlineSkills||[]).length>0,'a participating survivor earns the existing deathline awakening');
// Same progression with developed equipment and levels must allow a real victory, without changing the enemy reference.
game.resumeSavedGame(structuredClone(ten));game.closeStrategyModal();game.updateSpawns=noop;game.monsters=[];game.currentQuest=null;game.player.x=c+4000;game.player.y=c+4000;
for(const s of game.squad){s.level=18;s.reqExp=14000;s.hitGrowthPct=.35;s.weaponMastery={sword:1000,spear:1000,hammer:1000,bow:1000,crossbow:1000,cannon:1000};
  for(const [type,slot] of Object.entries(SLOT_INFO)){const item={id:`trained-${s.id}-${type}`,type,tier:3,name:'育成防衛装備',weaponStyle:s.equipped?.weapon?.weaponStyle||'sword',stats:{},rollMult:1};applyUpgradeStats(item,8);s.equipped[slot.key]=item;}
  game.recalcSoldierStats(s);s.hp=s.maxHp;
}
game.startDemonInvasion();game.arriveDemonInvasion();game.phaseTimer=65;const trainedArmy=[...game.squad];for(let i=0;i<1500&&game.invasions.stage==='battle';i++){simulationTime+=100;game.update(.1);}
console.log(JSON.stringify({case:'trained',lost:trainedArmy.filter(s=>s.dead||s.isDown).length,outcome:game.invasions.lastResult?.outcome}));assert.equal(game.invasions.lastResult?.outcome,'victory');assert.ok(trainedArmy.filter(s=>!s.dead&&!s.isDown).length>=36,'training can overcome a major invasion instead of causing stronger matching enemies');
// A basic captain's real manual attacks and one recovery potion cannot trivialize a major assault.
game.resumeSavedGame(structuredClone(ten));game.closeStrategyModal();game.updateSpawns=noop;game.monsters=[];game.currentQuest=null;game.player.x=c;game.player.y=c;game.startDemonInvasion();game.arriveDemonInvasion();game.phaseTimer=65;
for(let i=0;i<1800&&game.invasions.stage==='battle'&&game.inBattle;i++){simulationTime+=100;game.manualAttack();if(i%10===0)game.triggerPowerAttack();if(game.player.hp<game.player.maxHp*.5&&game.squadPotion)game.useSquadPotion();game.update(.1);}
console.log(JSON.stringify({case:'basic-captain',hp:game.player.hp,outcome:game.invasions.lastResult?.outcome||'battle'}));assert.ok(game.player.hp<=0||game.invasions.lastResult?.outcome!=='victory','a basic captain cannot win by simply standing at HQ and pressing attacks');
// Rescued town guards stay at HQ; a new individual replaces the vacant station after two waves, including reloads.
fresh();const town=game.dungeons.find(d=>d.id==='royal_castle_town');game.player.x=town.entrance.x;game.player.y=town.entrance.y;game.enterDungeon(town);const rescued=game.gateGuards.find(g=>g.gateSpace===town.id);const postId=rescued.gatePostId;markSoldierDown(game,rescued);game.player.x=rescued.x;game.player.y=rescued.y;updateWounded(game,0);game.exitDungeon();game.player.x=c;game.player.y=c;syncDragged(game,.1);updateWounded(game,0);assert.equal(rescued.rescuedToBase,true);const pending=game.gatePosts.find(p=>p.id===postId);assert.equal(pending.refillAtPhase,3);assert.equal(replenishTownGateGuards(game),0);
let data=structuredClone(game.saveGame());game.resumeSavedGame(data);game.phase=2;assert.equal(replenishTownGateGuards(game),0);game.phase=3;assert.equal(replenishTownGateGuards(game),1);const replacement=game.gateGuards.find(g=>g.gatePostId===postId&&!g.rescuedToBase&&!g.dead);assert.ok(replacement);assert.notEqual(replacement.id,rescued.id);assert.equal(replacement.gateSpace,town.id);assert.equal(replenishTownGateGuards(game),0);assert.equal(game.gateGuards.find(g=>g.id===rescued.id).rescuedToBase,true);
data=structuredClone(game.saveGame());game.resumeSavedGame(data);assert.ok(game.gateGuards.some(g=>g.id===replacement.id));assert.equal(game.gateGuards.filter(g=>g.gatePostId===postId&&!g.rescuedToBase&&!g.dead).length,1);
// Entrance guards also refill; downed guards at their posts do not get duplicated.
const outer=game.gateGuards.find(g=>g.gateTownId===town.id&&g.gateOrigin==='field'&&!g.rescuedToBase);markSoldierDown(game,outer);game.phase=10;assert.equal(replenishTownGateGuards(game),0);outer.dead=true;outer.isDown=false;game.onGateGuardRelocated(outer);game.phase=12;assert.equal(replenishTownGateGuards(game),1);assert.ok(game.gateGuards.some(g=>g.gatePostId===outer.gatePostId&&g.id!==outer.id&&!g.dead));
const oldSave=structuredClone(initial);delete oldSave.gatePosts;for(const g of oldSave.gateGuards){delete g.gatePostId;delete g.gateTownId;}game.resumeSavedGame(oldSave);assert.ok(game.gateGuards.every(g=>g.gatePostId));assert.ok(serializeGatePosts(game).length>5);assert.ok(serializeGateGuards(game).every(g=>g.gatePostId));
console.log('PASS: post-wave-10 majors, fixed bounded reference and saves, live default devastation/deathline survivor and trained defense, distinct two-wave town replacements/HQ residents/cooldowns/death/down/save/migration');Math.random=originalRandom;Date.now=originalDateNow;Object.defineProperty(globalThis,'performance',{configurable:true,value:originalPerformance});dom.window.close();
