import assert from 'node:assert/strict';
import {viewport,strokeVisibleRing,circleInView,persistentUnit} from '../js/games/iron-squad/render-support.js';
import {saveSlots} from '../js/games/iron-squad/save-slots.js';
import {WORLD_SIZE,WorldTerrain} from '../js/games/iron-squad/world.js';
const memory=new Map(),noop=()=>{};
globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
globalThis.window={devicePixelRatio:1,addEventListener:noop};
let arcArgs;const context=new Proxy({measureText:()=>({width:40}),arc(...args){arcArgs=args;},createRadialGradient:()=>({addColorStop:noop}),createLinearGradient:()=>({addColorStop:noop})},{get:(o,k)=>k in o?o[k]:noop});
const nodes=new Map();globalThis.document={createElement:()=>({width:1,height:1,getContext:()=>context}),getElementById:id=>{if(!nodes.has(id))nodes.set(id,{classList:{add:noop,remove:noop,toggle:noop},style:{},setAttribute:noop});return nodes.get(id);}};
const {IronSquadGame,DEPLOYMENT_CAPACITY,ENEMY_LIMIT}=await import('../js/games/iron-squad/index.js');
const view=viewport({x:0,y:0},390,664);
assert.equal(strokeVisibleRing(context,0,0,48000,view),false);
const edge=viewport({x:48000,y:0},390,664);
assert.equal(strokeVisibleRing(context,0,0,48000,edge),true);
assert.ok((arcArgs[4]-arcArgs[3])*48000<1000,'only the visible arc is tessellated');
assert.equal(circleInView(10000,10000,150,view),false);
const game=Object.create(IronSquadGame);
for(const name of ['updateStatsUI','updateQuestUI','startGameLoop','showToast'])game[name]=noop;
game.width=390;game.height=664;game.zoom=1;game.ctx=context;game.joystick={active:false,dirX:0,dirY:0};game.commandActiveUntil=0;
game.activeSlotId=saveSlots.create('performance').id;game.startFreshGame(false);
assert.equal(game.squad.length,DEPLOYMENT_CAPACITY);assert.equal(game.monsters.length,ENEMY_LIMIT);
const center=WORLD_SIZE/2,soldier=game.squad[0];game.squad=[soldier];game.rankIndex=2;
Object.assign(soldier,{x:center,y:center,hp:10000,maxHp:10000,isNamed:true,_pgTick:0});
game.player.x=center+300;game.player.y=center;game._guardAssignClock=1;
const monster={x:center-90,y:center,hp:1e9,maxHp:1e9,type:'goblin',radius:11,speed:0,atk:1};game.monsters=[monster];game.updateSpawns=noop;
assert.doesNotThrow(()=>game.update(1/60),'full update must not hit the BASE_TERRITORY_RADIUS TDZ');
assert.ok(soldier.isPersonalGuard);assert.ok(soldier.x<center,'even light AI frames approach a nearby enemy rather than orbit in the opposite direction');
assert.equal(DEPLOYMENT_CAPACITY,48);assert.equal(ENEMY_LIMIT,40,'population unchanged by this performance fix');
soldier._cachedEnemy=monster;monster._cachedTarget=soldier;
assert.doesNotThrow(()=>JSON.stringify(persistentUnit(soldier)));
game.saveGame();let saved=saveSlots.get(game.activeSlotId).data;
assert.ok(saved.squad[0]);assert.equal(saved.squad[0]._cachedEnemy,undefined);
game.restTimer=3;game.restMonsters=[monster];game.saveGame();saved=saveSlots.get(game.activeSlotId).data;
assert.equal(saved.restMonsters[0]._cachedTarget,undefined);
assert.equal(saved.restMonsters[0].hp,monster.hp);
game.camera={x:center+20000,y:center+20000};let outposts=0,camp=0;
game.drawOutpost=()=>outposts++;game.drawBaseCamp=()=>camp++;game.render();
assert.equal(outposts,0);assert.equal(camp,0,'offscreen camp and outposts do not issue draw commands');
// A broken frame must not repeatedly throw and silently advance timers forever.
let scheduled,requests=0;globalThis.requestAnimationFrame=fn=>{scheduled=fn;requests++;return 1;};globalThis.cancelAnimationFrame=noop;
let draws=0;const paused=Object.create(IronSquadGame);paused.inBattle=false;paused.update=noop;paused.render=()=>draws++;paused.renderMinimap=noop;
IronSquadGame.startGameLoop.call(paused);scheduled(performance.now()+16);scheduled(performance.now()+32);scheduled(performance.now()+48);
assert.equal(draws,1,'paused dialogs do not repaint the army every frame');paused.inBattle=true;scheduled(performance.now()+64);assert.equal(draws,2);paused.stopGameLoop();requests=0;
const failing=Object.create(IronSquadGame);failing.update=()=>{throw new Error('fixture');};failing.saveGame=noop;failing.showToast=noop;
const log=console.error;console.error=noop;
try {IronSquadGame.startGameLoop.call(failing);scheduled(performance.now()+16);assert.equal(failing.running,false);assert.equal(requests,1);}finally{console.error=log;}
const terrain=new WorldTerrain();const original=JSON.stringify(terrain.get(0,0).objects);
for(let y=0;y<6;y++)for(let x=0;x<6;x++)terrain.get(x,y);
assert.ok(terrain.tiles.size<=24);assert.equal(JSON.stringify(terrain.get(0,0).objects),original,'evicted scenery regenerates identically');
console.log('PASS: complete battle update, continuous close-combat movement, circular-cache-free saves, bounded ring paths, offscreen culling, no repeated failed frames, populations preserved');
