import assert from 'node:assert/strict';
import {saveSlots} from '../js/games/iron-squad/save-slots.js';
import {REST_DURATION,SOLDIER_SALARY,advanceRest,advancePhase,participated} from '../js/games/iron-squad/phase-rules.js';
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
globalThis.window={};globalThis.document={getElementById:()=>null};
const {IronSquadGame,applyUpgradeStats}=await import('../js/games/iron-squad/index.js');
const game=Object.create(IronSquadGame);
for(const method of ['recalcSoldierStats','recalcPlayerStats','updateStatsUI','updateQuestUI','startGameLoop','showToast','spawnSparks','spawnDamageText','renderStrategyUI'])game[method]=()=>{};
game.activeSlotId=saveSlots.create('休息検証').id;game.startFreshGame(false);
const soldier=game.squad[0];soldier.gold=100;soldier.hp=soldier.maxHp;
for(const item of Object.values(soldier.equipped))if(item)applyUpgradeStats(item,0);
const beforeGold=soldier.gold;
const boss={id:'boss',x:7000,y:7000,hp:1234,maxHp:2000,isBoss:true};game.monsters=[boss];game.projectiles=[{hostile:true}];
game.completePhase();const phase=game.phase,capacity=game.squad.length+game.reserves.length;
assert.equal(game.restTimer,REST_DURATION);assert.equal(soldier.gold,beforeGold+SOLDIER_SALARY);
assert.equal(game.monsters.length,0);assert.equal(game.projectiles.length,0);assert.equal(game.restMonsters[0].hp,1234);
assert.equal(game.phaseTimer,120);const time=game.totalBattleTime;
game.updateSpawns(99);game.spawnMonster(5500,5400);game.spawnColossalBoss();assert.equal(game.monsters.length,0);
game.completePhase();assert.equal(game.phase,phase);assert.equal(soldier.gold,beforeGold+SOLDIER_SALARY,'rest cannot trigger duplicate salary');
game.update(.5);assert.equal(game.restReport.count,0);
game.update(.5);assert.ok(soldier.lastMaintenance.count>0);assert.ok(game.restReport.count>0);
assert.equal(game.totalBattleTime,time);assert.equal(game.phaseTimer,120);assert.equal(participated(soldier),false);
assert.equal(game.squad.length+game.reserves.length,capacity);
assert.equal(advancePhase(game,999),false,'combat clock is held during rest');
game.inBattle=false;const paused=game.restTimer,spent=game.restReport.spent;advanceRest(game,4);game.update(4);
assert.equal(game.restTimer,paused);assert.equal(game.restReport.spent,spent,'meeting does not spend money in background');game.inBattle=true;
// Manual weapon enhancement stays available, even while the rest clock is paused.
soldier.gold+=500;game.upgradeSoldierEquip(soldier.id,'weapon');const manual=soldier.equipped.weapon.upgrade;assert.ok(manual>0);
game.update(1.5);game.saveGame();const saved=saveSlots.get(game.activeSlotId).data;
const savedGold=soldier.gold,savedCount=game.restReport.count,savedTimer=game.restTimer;
game.resumeSavedGame(saved);
assert.equal(game.restTimer,savedTimer);assert.equal(game.monsters.length,0);assert.equal(game.restReport.count,savedCount);
assert.equal(game.squad[0].gold,savedGold,'loading does not repay salary or repeat upgrades');
assert.equal(game.restMonsters[0].hp,1234);
advanceRest(game,savedTimer);assert.equal(game.restTimer,0);assert.equal(game.phaseTimer,120);assert.equal(game.phase,phase);
assert.equal(game.monsters[0].hp,1234,'unfinished boss retains damage across rest');
advancePhase(game,1);assert.equal(game.phaseTimer,119);
// Insufficient money, downed units and maximum enhancement produce explicit reasons.
const poor=game.squad[0];poor.gold=0;game.restReport={phase:phase,count:0,spent:0,trainedIds:[],salary:20};game.processRestSecond();
assert.match(poor.lastMaintenance.status,/資金不足/);assert.equal(poor.gold,0);
poor.isDown=true;game.processRestSecond();assert.match(poor.lastMaintenance.status,/負傷/);poor.isDown=false;
for(const item of Object.values(poor.equipped))if(item)applyUpgradeStats(item,30);poor.gold=999999;game.processRestSecond();
assert.match(poor.lastMaintenance.status,/上限/);assert.equal(poor.gold,999999);
console.log('PASS: 8-second safe rest, regular soldier salary, staggered self-upgrades, combat pause, manual forge, save/resume, boss preservation, budget and cap reasons');
