import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from '../../__pycache__/ui-tools/node_modules/jsdom/lib/api.js';
import {resetBattleLog,BATTLE_LOG_LIMIT,showsOnFieldLog,refreshCombatFieldNotes} from '../js/battle-log.js';
import {markSoldierDown,updateWounded} from '../js/casualty-rules.js';
import {AMMO_CAPACITY} from '../js/supply-rules.js';
const css=['game-ui','iron-squad','iron-squad-interface'].map(n=>readFileSync(new URL(n==='game-ui'?`../../common/css/${n}.css`:`../css/${n}.css`,import.meta.url),'utf8')).join('\n');
const dom=new JSDOM(`<style>${css}</style><div id="game" class="game-container iron-squad"></div>`,{url:'http://localhost/'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,screen:{}});
const noop=()=>{},ctx=new Proxy({measureText:()=>({width:40}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>k in o?o[k]:noop});
window.HTMLCanvasElement.prototype.getContext=()=>ctx;
const {IronSquadGame}=await import('../js/index.js'),{saveSlots}=await import('../js/save-slots.js');
const game=Object.create(IronSquadGame);Object.assign(game,{container:document.getElementById('game'),width:390,height:774,zoom:1,ctx,camera:{x:79360,y:79360},commandActiveUntil:0,selectedSaleIds:new Set(),joystick:{active:false,dirX:0,dirY:0}});
for(const key of ['startGameLoop','spawnDamageText','spawnSparks'])game[key]=noop;
game.setupUI();game.activeSlotId=saveSlots.create('LOG CONTROLS TEST ONLY').id;game.startFreshGame(false);const initial=structuredClone(game.saveGame());resetBattleLog(game);
assert.equal(showsOnFieldLog('衛生救護！兵士が戦線復帰'),false);
assert.equal(showsOnFieldLog('強敵を撃破！'),false);
assert.equal(showsOnFieldLog('装備を購入した'),false);
assert.equal(showsOnFieldLog('😈 [T1 鉄] 短剣 を横取り！'),true);
assert.equal(showsOnFieldLog('👑【ボス戦利品獲得！】[T3 鉄] 剣！'),true);
assert.equal(showsOnFieldLog('💠【神話秘宝！】入手'),true);
assert.equal(showsOnFieldLog('📦【国庫買取】[T1] 兜'),true);
assert.equal(showsOnFieldLog('隊長のHPが半分以下 · 残り40/100'),true);
assert.equal(showsOnFieldLog('アランのMPが半分以下 · 残り10/40'),true);
assert.equal(showsOnFieldLog('アランの残り弾薬が半分以下 · 12/30'),true);
assert.equal(showsOnFieldLog('アランの死亡まで残り14秒'),true);
assert.equal(showsOnFieldLog('アランは力尽きました'),true);
assert.equal(showsOnFieldLog('行商人は力尽きました',{field:false}),false);
const stream=document.getElementById('battle-log-stream'),logWindow=document.getElementById('battle-log-window'),originalSet=globalThis.setTimeout,originalClear=globalThis.clearTimeout,pending=new Map();let sequence=0;
const mockTimers=()=>{globalThis.setTimeout=fn=>{const id=++sequence;pending.set(id,fn);return id;};globalThis.clearTimeout=id=>pending.delete(id);};
const restoreTimers=()=>{globalThis.setTimeout=originalSet;globalThis.clearTimeout=originalClear;game._battleLogTimer=null;};
try{
  mockTimers();
  game.showToast('以前の通知');
  for(let i=0;i<130;i++)game.showToast(`衛生救護！兵士${i}が戦線復帰。報酬と武勲を含む長い通知。`.repeat(4));
  assert.equal(stream.children.length,0,'rescue bursts stay in history and off the field');
  assert.equal(pending.size,0,'hidden notices do not keep a field timer');
  assert.equal(game.battleLogHistory.length,BATTLE_LOG_LIMIT);
  assert.match(game.battleLogHistory[0].text,/兵士30/);assert.equal(new Set(game.battleLogHistory.map(e=>e.id)).size,BATTLE_LOG_LIMIT);
  assert.equal(window.getComputedStyle(logWindow).display,'none');
  assert.equal(window.getComputedStyle(logWindow).gridRow,'3');
}finally{restoreTimers();}
document.getElementById('btn-battle-log-history').click();
assert.equal(document.getElementById('strategy-modal').classList.contains('hidden'),false);assert.equal(document.getElementById('command-battle-log').open,true);
assert.equal(document.querySelectorAll('#battle-log-history > li').length,100);assert.match(document.getElementById('battle-log-history').lastElementChild.textContent,/兵士129/);
assert.equal(game.inBattle,false,'history uses the existing paused headquarters');assert.equal(game.joystick.active,false);
game.closeStrategyModal();
try{
  mockTimers();
  game.showToast('😈 [T1 鉄] 短剣 を横取り！');
  assert.equal(stream.children.length,1);assert.match(stream.textContent,/横取り/);
  assert.equal(window.getComputedStyle(stream.firstElementChild).whiteSpace,'nowrap');
  assert.equal(window.getComputedStyle(stream.firstElementChild).textOverflow,'ellipsis');
  assert.equal(window.getComputedStyle(logWindow).display,'block');
  assert.ok(logWindow.classList.contains('has-field-note'));
  assert.equal(window.getComputedStyle(document.getElementById('btn-battle-log-history')).display,'none');
  const stale=pending.get(game._battleLogTimer);
  game.showToast('隊長のHPが半分以下 · 残り40/100');
  stale();assert.notEqual(stream.firstElementChild.style.opacity,'0','an old notification cannot hide the latest message');
  assert.ok(logWindow.classList.contains('has-field-note'));
  game.showToast('強敵を撃破！');game.showToast('装備を購入した');
  assert.match(stream.textContent,/HPが半分以下/,'ordinary combat notices do not replace the field line');
  game.player.maxHp=100;game.player.hp=100;game.player.maxMana=100;game.player.mana=100;game.player.ammo=AMMO_CAPACITY;
  const shooter=game.squad[1];
  shooter.soldierClass='ARCHER';shooter.combatClass='ARCHER';shooter.dead=false;shooter.isDown=false;shooter.hp=shooter.maxHp||80;shooter.maxHp=shooter.hp;shooter.maxMana=80;shooter.mana=80;shooter.ammo=AMMO_CAPACITY;
  const halfMarks=()=>game.battleLogHistory.filter(e=>/半分以下/.test(e.text)).length;
  const halfBefore=halfMarks();
  refreshCombatFieldNotes(game);
  assert.equal(halfMarks(),halfBefore,'the first look only remembers who is already low');
  game.player.hp=50;refreshCombatFieldNotes(game);assert.match(stream.textContent,/隊長のHPが半分以下 · 残り50\/100/);
  refreshCombatFieldNotes(game);assert.equal(halfMarks(),halfBefore+1);
  game.player.hp=100;refreshCombatFieldNotes(game);game.player.hp=40;refreshCombatFieldNotes(game);
  assert.equal(halfMarks(),halfBefore+2);
  shooter.mana=30;refreshCombatFieldNotes(game);assert.match(stream.textContent,/MPが半分以下 · 残り30\/80/);
  shooter.ammo=Math.floor(AMMO_CAPACITY/2);refreshCombatFieldNotes(game);assert.match(stream.textContent,new RegExp(`残り弾薬が半分以下 · ${shooter.ammo}/${AMMO_CAPACITY}`));
  refreshCombatFieldNotes(game);assert.equal(game.battleLogHistory.filter(e=>e.text.includes(`${shooter.name}の残り弾薬が半分以下`)).length,1);
  const ally=game.squad[0];ally.x=1000;ally.y=1000;markSoldierDown(game,ally);ally.downTimer=16;
  updateWounded(game,2);assert.match(stream.textContent,/死亡まで残り/);
  updateWounded(game,.2);assert.equal(game.battleLogHistory.filter(e=>/死亡まで残り/.test(e.text)).length,1);
  ally.downTimer=.4;updateWounded(game,1);updateWounded(game,2.1);assert.match(stream.textContent,new RegExp(`${ally.name}は力尽きました`));
  const merchant={id:'merchant-field-log',name:'行商人',isMerchant:true,isDown:true,dead:false,hp:0,maxHp:40,downTimer:.3,x:1200,y:1200};
  game._merchantWounded=[merchant];updateWounded(game,1);updateWounded(game,2.1);
  assert.equal(merchant.dead,true);assert.doesNotMatch(stream.textContent,/行商人は力尽きました/);
  assert.ok(game.battleLogHistory.some(e=>e.text.includes('行商人は力尽きました')));
  pending.get(game._battleLogTimer)?.();assert.equal(logWindow.classList.contains('has-field-note'),false);
  assert.equal(window.getComputedStyle(logWindow).display,'none');
}finally{restoreTimers();}
const potion=document.getElementById('btn-pad-potion');
assert.ok(potion.closest('.pad-move-column'));assert.equal(potion.closest('.pad-buttons-zone'),null,'potion is separated from attack controls');assert.equal(window.getComputedStyle(potion).height,'48px');
game.player.hp=10;game.squadPotion=1;game.inBattle=true;potion.click();assert.equal(game.squadPotion,0);assert.equal(game.player.hp,game.player.maxHp);potion.click();assert.equal(game.squadPotion,0);
game.resumeSavedGame(initial);assert.ok(!game.battleLogHistory.some(e=>e.text.includes('兵士129')),'history does not cross into a different resumed expedition');
clearTimeout(game._battleLogTimer);dom.window.close();
console.log('PASS: field notes only for drops, half HP/MP/ammo, the 15s down warning and soldier deaths; rescue bursts stay in the 100-entry history; stale timers, headquarters history, 48px potion and expedition reset');
