import assert from 'node:assert/strict';
import fs from 'node:fs';
import {formatDistance,formatSpeed,formatLength,formatLengthDelta,UNITS_PER_METER} from '../js/distance-format.js';
assert.equal(UNITS_PER_METER,100);
assert.equal(formatDistance(48000),'480m');
assert.equal(formatDistance(8000),'80m');
assert.equal(formatDistance(1234567),'12,346m');
assert.equal(formatDistance(49),'0m');
assert.equal(formatDistance(150),'2m');
assert.equal(formatDistance(undefined),'0m');
assert.ok(!/\./.test(formatDistance(48049)));
assert.equal(formatSpeed(100),'1.0m/秒');
assert.notEqual(formatSpeed(100),formatSpeed(115));
assert.equal(formatLength(145),'1.45m');
assert.equal(formatLength(80),'0.80m');
assert.equal(formatLengthDelta(15),'+0.15m');
assert.equal(formatLengthDelta(-30),'-0.30m');
const dir='../js/';
const read=f=>fs.readFileSync(new URL(dir+f,import.meta.url),'utf8');
assert.ok(!/\}m[\s·\)`'"]/.test(read('troop-rankings.js').replace(/\$\{[^}]*\}m\/秒/g,'')),'no raw m');
assert.ok(!/Math\.round\(distToBase\)\}m/.test(read('index.js')));
assert.ok(!read('index.js').includes('メートル換算）\n'),'comment fixed');
assert.ok(!/TALENTS[\s\S]{0,2500}expMult/.test(read('index.js').slice(read('index.js').indexOf('export const TALENTS'),read('index.js').indexOf('export const TALENTS')+2500)),'talent expMult removed');
console.log('distance-format.test: PASS');
