import assert from 'node:assert/strict';
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
globalThis.window={};globalThis.document={getElementById:()=>null};
const {IronSquadGame,SOLDIER_CLASSES,applyUpgradeStats}=await import('../js/index.js');
const {saveSlots}=await import('../js/save-slots.js');
const {rollHeroRevelation,initializeHeroJourney}=await import('../js/hero-party.js');
const {grantHeroEquipment,HERO_EQUIPMENT_RULES,heroEquipmentSummary}=await import('../js/hero-equipment.js');
const {canUseWeapon}=await import('../js/weapon-requirements.js');
const {canSell}=await import('../js/equipment-rules.js');
const {soldierEquipmentValue}=await import('../js/armament-rules.js');
const {equipmentVisualProfile}=await import('../js/equipment-tiers.js');
const {attributeValues}=await import('../js/unit-attributes.js');
const game=Object.create(IronSquadGame);
for(const m of ['updateStatsUI','updateQuestUI','startGameLoop','showToast','spawnDamageText','spawnSparks','renderStrategyUI','refreshSupplyUI'])game[m]=()=>{};
game.activeSlotId=saveSlots.create('勇者装備検証').id;game.startFreshGame(false);game.phase=10;rollHeroRevelation(game,()=>0);
const p=game.heroJourney.party,armyBefore=JSON.stringify(game.squad);
assert.ok(p.members.every(u=>u.heroEquipmentVersion===HERO_EQUIPMENT_RULES.version));
assert.ok(p.members.every(u=>Object.values(u.equipped).filter(Boolean).every(i=>i.heroOnly)));
assert.ok(p.members.every(u=>u.level===1&&u.maxHp>7000&&u.def>5000));
assert.equal(p.members[0].equipped.weapon.weaponStyle,'sword');
assert.equal(p.members.find(u=>u.soldierClass==='ARCHER').equipped.weapon.weaponStyle,'bow');
assert.equal(p.members.find(u=>u.soldierClass==='MEDIC').equipped.weapon.weaponStyle,'staff');
assert.equal(p.members.find(u=>u.soldierClass==='MAGE').equipped.weapon.weaponStyle,'wand');
assert.ok(p.members.every(u=>u.magicDef>4000));assert.ok(p.journal.events.some(e=>e.type==='equipment'));assert.ok(p.journal.startMembers[0].equipment.length>=6);
const normal=game.squad[0],hero=p.members[0],weapon=hero.equipped.weapon,armor=hero.equipped.armor;
assert.equal(canUseWeapon(game.player,weapon),false,'historical isHero flag does not grant access');
assert.equal(canUseWeapon(normal,weapon),false);assert.equal(canUseWeapon(normal,armor),false);assert.equal(canUseWeapon(hero,weapon),true);
assert.equal(soldierEquipmentValue(game,normal,armor,'armor',SOLDIER_CLASSES),-Infinity);
const equipped=game.equipped.weapon;assert.equal(game.equipItem(weapon),false);assert.equal(game.equipped.weapon,equipped);
assert.equal(game.equipItem(armor),false);assert.equal(canSell({...weapon,favorite:false},new Set()),false);
const count=hero.heroRetiredEquipment.length;assert.equal(grantHeroEquipment(game,hero),false);assert.equal(hero.heroRetiredEquipment.length,count);
assert.equal(JSON.stringify(game.squad),armyBefore,'normal army does not receive the special stats');
const atk=weapon.stats.atk;applyUpgradeStats(weapon,2);assert.equal(weapon.stats.atk,Math.floor(atk*1.5));assert.equal(weapon.minStrength,0);assert.equal(weapon.heroOnly,true);
assert.equal(equipmentVisualProfile(weapon).coverage,1);
const expectedMagic=attributeValues(hero).magicDefense+hero.equipped.amulet.stats.magicDefense;assert.equal(hero.magicDef,expectedMagic);
const saved=game.saveGame();game.resumeSavedGame(JSON.parse(JSON.stringify(saved)));assert.equal(game.heroJourney.party.members[0].equipped.weapon.upgrade,2);assert.equal(game.heroJourney.party.members[0].heroRetiredEquipment.length,count);
// An existing active party receives equipment once; retired pieces and down state remain.
const legacy=structuredClone(saved.heroJourney);for(const u of legacy.party.members){u.heroEquipmentVersion=0;u.equipped={weapon:u.heroRetiredEquipment[0]};u.weapon=u.equipped.weapon;}
legacy.party.members[0].isDown=true;legacy.party.members[0].hp=0;initializeHeroJourney(game,legacy);assert.equal(game.heroJourney.party.members[0].hp,0);assert.equal(game.heroJourney.party.members[0].isDown,true);assert.ok(heroEquipmentSummary(game.heroJourney.party.members[0]).length>=6);
console.log('hero-equipment: full grant, class weapons, exclusive access, magic defense, visual profile, upgrades, save and migration passed');
