// v4.2.20: the commander can walk during the rest between rounds; enemies, spawns and the phase clock stay frozen.
import assert from 'node:assert/strict';
import {saveSlots} from '../js/save-slots.js';
import {REST_DURATION} from '../js/phase-rules.js';
const memory=new Map();globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
globalThis.window={};globalThis.document={getElementById:()=>null};
const {IronSquadGame}=await import('../js/index.js');
const game=Object.create(IronSquadGame);
for(const method of ['recalcSoldierStats','recalcPlayerStats','updateStatsUI','updateQuestUI','startGameLoop','showToast','spawnSparks','spawnDamageText','renderStrategyUI'])game[method]=()=>{};
game.activeSlotId=saveSlots.create('待機移動').id;game.startFreshGame(false);
const boss={id:'boss',x:7000,y:7000,hp:1234,maxHp:2000,isBoss:true};game.monsters=[boss];
game.completePhase();
assert.equal(game.restTimer,REST_DURATION);assert.equal(game.monsters.length,0,'enemies are put aside during rest');
const phaseTimer=game.phaseTimer,battle=game.totalBattleTime,hp=game.restMonsters[0].hp;
const x0=game.player.x,y0=game.player.y;
game.joystick={active:true,x:1,y:0,dirX:1,dirY:0};
for(let i=0;i<10;i++)game.update(.1);
assert.ok(game.player.x>x0+50,`player walks during rest (${x0} -> ${game.player.x})`);
assert.ok(game.restTimer<REST_DURATION&&game.restTimer>0,'rest clock keeps running');
assert.equal(game.monsters.length,0,'no spawns');assert.equal(game.restMonsters[0].hp,hp);assert.equal(game.restMonsters[0].x,7000);assert.equal(game.restMonsters[0].y,7000);
assert.equal(game.phaseTimer,phaseTimer,'phase timer held');assert.equal(game.totalBattleTime,battle);
game.enterDungeon({kind:'dungeon',entrance:{x:0,y:0,radius:1}});assert.equal(game.currentDungeon??null,null,'dungeon entry is blocked during rest');
game.joystick.active=false;
game.update(REST_DURATION);
assert.equal(game.restTimer,0);assert.equal(game.monsters[0].hp,1234,'enemies return after rest');
console.log('rest-movement tests passed');
